# Generated by Django 5.1.3 on 2024-11-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_category_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
