# Generated by Django 5.1.3 on 2024-11-29 09:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_blog_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_image', models.ImageField(upload_to='Image/publication')),
                ('self_name', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('topic', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
