# Generated by Django 5.1.3 on 2024-11-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
