# Generated by Django 5.1.3 on 2024-11-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
