# Generated by Django 5.1.3 on 2024-11-30 00:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_image', models.ImageField(upload_to='Images/author')),
                ('self_name', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('topic', models.CharField(max_length=30)),
                ('goal', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Images/blog')),
                ('title', models.CharField(max_length=60)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
