# Generated by Django 5.1.3 on 2024-11-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='self_image',
            field=models.ImageField(default='images/default.png', upload_to='Images/author'),
        ),
    ]
