# Generated by Django 5.1.3 on 2024-12-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_blog_self_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
