# Generated by Django 5.1.3 on 2024-12-01 07:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/portfolio')),
                ('title', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('topic', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
