# Generated by Django 5.1.3 on 2024-12-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topic',
        ),
    ]
